version: '3.8'

services:
  api-portal-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-portal-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - BACKEND_INTERNAL_URL=http://host.docker.internal:4010
